notifications:
  email: false
sudo: required
services:
- docker
language: python
python:
- 3.6
env:
  global:
  - DOCKER_LABEL=$TRAVIS_BRANCH
  - DOCKER_PUSH_LATEST=true
  - DOCKER_REPOSITORY=renku/
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.8.2-linux-amd64.tar.gz
  - secure: SJRGvfdP8JDMWEza+0Gb/wlRPizrg0fo+uvPJXr/SiHFzuGHwoR9DJoIdxvX/7YxTrnLQJwKBfWsPA9NU7XnqzT0NtbKt4g3gJzaK0d3/IdhgmbFG0+zj32tPek1XvHGzH760xa6a/owL0ukMuFW9eKU5Nv34hb1m6xjxQUWCU4Jd1mq0PLOb7CxzEj5+6MHYlJ+QlZp4kDAZY9YdMynjr3jXft3ZVPM5je6pZ15aA3RVhAeGSwJS7byx5oXTstof9mRVvME1qC4uUWqpxuqf1A+dORp7Iyyf5Gu3SINdtoqTC5PY1ViY60FBdwpGZRrUfwHemgb1qNSwb1LX7NevB5NwkMtpyfxfrVyTDD43DrUNvPMGh4evWifzv6diN3umuXq9FyoVi0jzHM3p+lCOdwPki7jKzUq5j3IQOQ9zbQnamltsasmPsOtUF4d309NHt2R5pbOaVyG+ogNLPb6DaCUw+Ef2rAEg0Z41Ld0i+SEL5w1Q3lhYS8MsWb2yu+UIeSMXKbiqXoVkRNjxfBLslaJKT6znwdHfgYSA+M5o+OB6PbPFyRjgBTyvZ253WUuGrqbvkP0TUyaNZhI0oyJhgnDPqT0NyVr0z1xiTFCnBKvwwdZUcomjjAMNsfswthl+/cUs4zr7PS4BeNPVJqoCEQfPQVwq5gmsUiTw/Tbwmo=
git:
  depth: false
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - nodejs
before_install:
- nvm install 'lts/*'; nvm use 'lts/*'
install:
- travis_retry pip install -U pip
- travis_retry pip install "chartpress==0.3.2" "ruamel.yaml==0.15.54" "docker==4.2.2"
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only
- npm ci
script:
- make tag/renku-ui
- make test/renku-ui
- helm lint helm-chart/renku-ui -f helm-chart/minikube-values.yaml
deploy:
- provider: script
  skip_cleanup: true
  script: bash  ./.travis/travis-deploy.sh
  on:
    branch: master
    repo: SwissDataScienceCenter/renku-ui
- provider: script
  skip_cleanup: true
  script: bash  ./.travis/travis-deploy.sh
  on:
    branch: master
    repo: SwissDataScienceCenter/renku-ui
    tags: true
