branches:
  only:
  - master
language: node_js
node_js:
- 'lts/*'
- 'node'
matrix:
  allow_failures:
  - node_js: 'node'
sudo: true
script:
- npm run build
- npm run lint
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./.travis/deploy-docker.sh
  on:
    branch: master

cache:
  directories:
    - node_modules
