gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'localhost'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost'
      gitlab_rails['lfs_enabled'] = true      
      gitlab_rails['lfs_storage_path'] = '/var/storage/lfs-objects'
      gitlab_rails['initial_root_password'] = 'root_password'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - './gitlab/config:/etc/gitlab'
    - './gitlab/logs:/var/log/gitlab'
    - './gitlab/git-data:/var/opt/gitlab'
    - './gitlab/lfs-data:/var/storage/lfs-objects'

ui:
  build: .
  restart: always
  links:
    - gitlab:dev.gitlab
  ports:
    - 5000:3000
  environment:
    - GITLAB_SECRET_TOKEN
  volumes:
      - ./src:/app/src
      - ./public:/app/public
