version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://docker.for.mac.localhost:5080'
        gitlab_rails['gitlab_shell_ssh_port'] = 5022
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['lfs_storage_path'] = '/var/storage/lfs-objects'
        gitlab_rails['initial_root_password'] = 'root_password'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '5080:5080'
      - '5443:443'
      - '5022:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/git-data:/var/opt/gitlab'
      - './gitlab/lfs-data:/var/storage/lfs-objects'

  ui:
    build: .
    restart: always
    links:
      - gitlab:dev.gitlab
    ports:
      - 5000:3000
    environment:
      - GITLAB_SECRET_TOKEN
    volumes:
      - ./src:/app/src
      - ./public:/app/public

  reverse-proxy:
    image: traefik
    command: --web --web.address=:81 \
      --docker --docker.watch --docker.domain=docker.for.mac.localhost \
      --debug --logLevel=DEBUG \
      --defaultentrypoints=http \
      --entrypoints='Name:http Address::8080' \
      --docker.exposedbydefault=false
    # FIXME usage of self signed certs --entrypoints='Name:http Address::80 Redirect.EntryPoint:https' \
    ports:
      - 8080:8080
      - 81:81
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - default
      - review

networks:
  review:
    external: true