# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global variables
## Shared values/secrets
global:

  renku:
    ## Domain name for the deployed instance of renku
    domain: example.local

  ## Set to true if using https
  useHTTPS: false

replicaCount: 1

image:
  repository: renku/renku-ui
  tag: '0.10.3'
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

welcomePage:
  text: |
    ## Welcome to Renku!
    Renku is software for collaborative data science. With Renku you can share code and data,
    discuss problems and solutions, and coordinate data-science projects.

templates:
  custom: true
  repositories:
    - url: https://github.com/SwissDataScienceCenter/renku-project-template
      ref: 0.1.11
      name: Renku

# Any string here, other than 'false', will enable the maintenance page and be added on it as an info.
# Setting 'true' will display a standard message embedded in maintenace page.
maintenance: false

sentry:
  enabled: false
  url: ''
  namespace: ''

privacy:
  enabled: false
  page:
    map: false
    configMapName: privacy-page
    configMapKey: privacy_statement
  banner:
    content: |
      This website requires cookies in order to ensure basic functionality. By clicking
      or navigating the site, you consent to the use of cookies in accordance with
      our <u><a class="text-white" href="/privacy">Privacy Policy</a></u>.
    layout:
      cookieName: RenkuLabPrivacy
      disableStyles: true
      containerClasses: fixed-bottom p-3 bg-dark
      contentClasses: text-white small
      buttonClasses: btn btn-sm btn-light mr-2
      buttonWrapperClasses: mt-2
