name: Acceptance tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed
    paths:
    - client/**
    - server/**
    - helm-chart/**

jobs:
  deploy-pr:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment:
      name: ci-ui-${{ github.event.number }}-renku
      url: "https://ci-ui-${{ github.event.number }}-renku.dev.renku.ch"
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      uses: SwissDataScienceCenter/renku/actions/deploy-renku@000-deploy-action
      env:
        RANCHER_PROJECT_ID: ${{ secrets.CI_RANCHER_PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
        RENKU_NAMESPACE: ci-ui-${{ github.event.number }}-renku
        RENKU_TMP_NAMESPACE: ci-ui-${{ github.event.number }}-renku-tmp
        RENKU_RELEASE: ci-ui-${{ github.event.number }}-renku
        RENKU_VALUES_FILE: "${{ github.workspace }}/values.yaml"
        RENKU_VALUES: ${{ secrets.CI_RENKU_VALUES }}
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKUBOT_RANCHER_BEARER_TOKEN: ${{ secrets.RENKUBOT_RANCHER_BEARER_TOKEN }}
        renku: "@000-deploy-action"
        renku_ui: "@${{ github.head_ref }}"

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - uses: SwissDataScienceCenter/renku/actions/teardown-renku@000-deploy-action
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_DEV_TOKEN }}
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        RENKU_RELEASE: "ci-ui-${{ github.event.number }}-renku"
        RENKU_NAMESPACE: "ci-ui-${{ github.event.number }}-renku"
        RENKU_TMP_NAMESPACE: "ci-ui-${{ github.event.number }}-renku-tmp"
