name: Acceptance tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed
    paths:
    - client/**
    - server/**
    - helm-chart/**

jobs:
  deploy-pr:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment:
      name: ci-renku-ui-${{ github.event.number }}
    steps:
    - uses: actions/checkout@v2
    - id: checkDeployComment
      uses: SwissDataScienceCenter/renku/actions/check-pr-description@000-deploy-action
      with:
        string: /deploy
        pr_ref: ${{ github.event.number }}
    - name: Find deplyoment url
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string }}
      uses: peter-evans/find-comment@v1
      id: deploymentUrlMessage
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "RenkuBot"
        body-includes: "You can access the deployment of this PR at"
    - name: Create comment deployment url
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string && steps.deploymentUrlMessage.outputs.comment-id == 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          You can access the deployment of this PR at https://ci-renku-ui-${{ github.event.number }}.dev.renku.ch
    - name: Build and deploy
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string }}
      uses: SwissDataScienceCenter/renku/actions/deploy-renku@000-deploy-action
      env:
        RANCHER_PROJECT_ID: ${{ secrets.CI_RANCHER_PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
        RENKU_NAMESPACE: ci-renku-ui-${{ github.event.number }}
        RENKU_TMP_NAMESPACE: ci-renku-ui-${{ github.event.number }}-tmp
        RENKU_RELEASE: ci-renku-ui-${{ github.event.number }}
        RENKU_VALUES_FILE: "${{ github.workspace }}/values.yaml"
        RENKU_VALUES: ${{ secrets.CI_RENKU_VALUES }}
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKUBOT_RANCHER_BEARER_TOKEN: ${{ secrets.RENKUBOT_RANCHER_BEARER_TOKEN }}
        renku: "@000-deploy-action"
        renku_ui: "@${{ github.head_ref }}"

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - id: checkDeployComment
      uses: SwissDataScienceCenter/renku/actions/check-pr-description@000-deploy-action
      with:
        string: /deploy
        pr_ref: ${{ github.event.number }}
    - name: Find deplyoment url
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string }}
      uses: peter-evans/find-comment@v1
      id: deploymentUrlMessage
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "RenkuBot"
        body-includes: "Tearing down the temporary RenkuLab deplyoment"
    - name: Create comment deployment url
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string && steps.deploymentUrlMessage.outputs.comment-id == 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Tearing down the temporary RenkuLab deplyoment for this PR.
    - uses: SwissDataScienceCenter/renku/actions/teardown-renku@000-deploy-action
      if: ${{ steps.checkDeployComment.outputs.pr-contains-string }}
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_DEV_TOKEN }}
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        RENKU_RELEASE: "ci-renku-ui-${{ github.event.number }}"
        RENKU_NAMESPACE: "ci-renku-ui-${{ github.event.number }}"
        RENKU_TMP_NAMESPACE: "ci-renku-ui-${{ github.event.number }}-tmp"
