name: Acceptance tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed
    paths:
    - client/**
    - server/**
    - helm-chart/**

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    outputs:
      pr-contains-string: ${{ steps.deploy-comment.outputs.pr-contains-string }}
    steps:
      - id: deploy-comment
        uses: SwissDataScienceCenter/renku/actions/check-pr-description@master
        with:
          string: /deploy
          pr_ref: ${{ github.event.number }}

  deploy-pr:
    needs: check-deploy
    if: github.event.action != 'closed' && needs.check-deploy.outputs.pr-contains-string == 'true'
    runs-on: ubuntu-latest
    environment:
      name: ci-ui-${{ github.event.number }}
    steps:
    - uses: actions/checkout@v2
    - name: Find deplyoment url
      uses: peter-evans/find-comment@v1
      id: deploymentUrlMessage
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "RenkuBot"
        body-includes: "You can access the deployment of this PR at"
    - name: Create comment deployment url
      if: steps.deploymentUrlMessage.outputs.comment-id == 0
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          You can access the deployment of this PR at https://ci-ui-${{ github.event.number }}.dev.renku.ch
    - name: Build and deploy
      uses: SwissDataScienceCenter/renku/actions/deploy-renku@master
      env:
        RANCHER_PROJECT_ID: ${{ secrets.CI_RANCHER_PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
        RENKU_RELEASE: ci-ui-${{ github.event.number }}
        RENKU_VALUES_FILE: "${{ github.workspace }}/values.yaml"
        RENKU_VALUES: ${{ secrets.CI_RENKU_VALUES }}
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKUBOT_RANCHER_BEARER_TOKEN: ${{ secrets.RENKUBOT_RANCHER_BEARER_TOKEN }}
        renku_ui: "@${{ github.head_ref }}"

  cleanup:
    needs: check-deploy
    if: github.event.action == 'closed' && needs.check-deploy.outputs.pr-contains-string == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Find deplyoment url
      uses: peter-evans/find-comment@v1
      id: deploymentUrlMessage
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "RenkuBot"
        body-includes: "Tearing down the temporary RenkuLab deplyoment"
    - name: Create comment deployment url
      if: steps.deploymentUrlMessage.outputs.comment-id == 0
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Tearing down the temporary RenkuLab deplyoment for this PR.
    - uses: SwissDataScienceCenter/renku/actions/teardown-renku@master
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_DEV_TOKEN }}
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKU_RELEASE: "ci-ui-${{ github.event.number }}"
