name: Acceptance tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed
    paths:
    - client/**
    - server/**
    - helm-chart/**

jobs:
  deploy-pr:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the latest commit on PR
      id: latestcommit
      uses: ActionsRML/get-PR-latest-commit@master
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: findcomment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'RenkuBot'
    - name: Create comment pre deploy
      if: ${{ steps.findcomment.outputs.comment-id == 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A deplyoment for this PR is being prepared based on the commit ${{ steps.latestcommit.outputs.latest_commit_sha }}.

          You will be able to access it at https://ci-ui-${{ github.event.number }}-renku.dev.renku.ch

          *If you try to access it now, it may be either unavailable or based on a previous commit.*
    - name: Update comment pre deploy
      if: ${{ steps.findcomment.outputs.comment-id != 0 }}
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        comment-id: ${{ steps.findcomment.outputs.comment-id }}
        edit-mode: replace
        body: |
          A deplyoment for this PR is being prepared based on the commit ${{ steps.latestcommit.outputs.latest_commit_sha }}.

          You will be able to access it at https://ci-ui-${{ github.event.number }}-renku.dev.renku.ch

          *If you try to access it now, it may be either unavailable or based on a previous commit.*
    - name: renku build and deploy
      uses: SwissDataScienceCenter/renku/actions/deploy-renku@000-deploy-action
      env:
        RANCHER_PROJECT_ID: ${{ secrets.CI_RANCHER_PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
        RENKU_NAMESPACE: ci-ui-${{ github.event.number }}-renku
        RENKU_TMP_NAMESPACE: ci-ui-${{ github.event.number }}-renku-tmp
        RENKU_RELEASE: ci-ui-${{ github.event.number }}-renku
        RENKU_VALUES_FILE: "${{ github.workspace }}/values.yaml"
        RENKU_VALUES: ${{ secrets.CI_RENKU_VALUES }}
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        RENKUBOT_RANCHER_BEARER_TOKEN: ${{ secrets.RENKUBOT_RANCHER_BEARER_TOKEN }}
        renku: "@development"
        renku_ui: "@${{ github.head_ref }}"
    - name: Update comment post deploy
      if: success()
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        comment-id: ${{ steps.findcomment.outputs.comment-id }}
        edit-mode: replace
        body: |
          A deployment is ready for this PR :tada:. Currently, the source commit is ${{ steps.latestcommit.outputs.latest_commit_sha }}.

          You can access it at https://ci-ui-${{ github.event.number }}-renku.dev.renku.ch
    - name: Update comment failed deploy
      if: failure()
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        comment-id: ${{ steps.findcomment.outputs.comment-id }}
        edit-mode: replace
        body: |
          Trying to create a deployment based on ${{ steps.latestcommit.outputs.latest_commit_sha }} resulted in a failure scream:

          The access to https://ci-ui-${{ github.event.number }}-renku.dev.renku.ch may be broken or outdated.

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
    - uses: SwissDataScienceCenter/renku/actions/teardown-renku@000-deploy-action
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_DEV_TOKEN }}
        KUBECONFIG: ${{ github.workspace }}/renkubot-kube.config
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_KUBECONFIG }}
        RENKU_RELEASE: "ci-ui-${{ github.event.number }}-renku"
        RENKU_NAMESPACE: "ci-ui-${{ github.event.number }}-renku"
        RENKU_TMP_NAMESPACE: "ci-ui-${{ github.event.number }}-renku-tmp"
