name: CI

on: [push]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '8.11'
    - name: Install dependencies and build
      run: |
        npm install
        npm run-script build
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
    - name: Run test
      run: npm test
      env:
        CI: true
    - name: Run lint
      run: npm run lint

  test-chart:
    # needs: test ! temporarily comment out for testing
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Test helm chart
        env:
          HELM_URL: https://storage.googleapis.com/kubernetes-helm
          HELM_TGZ: helm-v2.16.9-linux-amd64.tar.gz
          TEMP_DIR: ${{ runner.temp }}
        run: |
          wget -q ${HELM_URL}/${HELM_TGZ} -O ${TEMP_DIR}/${HELM_TGZ}
          tar -C ${TEMP_DIR} -xzv -f ${TEMP_DIR}/${HELM_TGZ}
          PATH=${TEMP_DIR}/linux-amd64/:$PATH
          helm init --client-only
          helm lint helm-chart/renku-ui -f helm-chart/minikube-values.yaml
      - name: Build chart and images
        run: |
          python -m pip install --upgrade pip "chartpress==0.3.2" "ruamel.yaml==0.15.54"
          chartpress
