name: CI

on: [push]

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '8.11'
    - name: Install dependencies and build
      run: |
        npm install
        npm run-script build
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
    - name: Run test
      run: npm test
      env:
        CI: true
    - name: Run lint
      run: npm run lint
